Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np
empty_arr_v2 = np.empty((2,2))
one_arr_v2 = np.ones((4,2))
print(empty_arr_v2)
print(one_arr_v2)
full_arr_v2 = np.full((2,2), 7)
print(full_arr_v2)
zeros_like_arr_v2 = np.zeros_like(one_arr_v2)
print(zeros_like_arr_v2)
ones_like_arr_v2 = np.ones_like(empty_arr_v2)
print(ones_like_arr_v2)
new_list_v2 = [1,2,3,4]
arr_list_v2 = np.array(new_list_v2)
print(arr_list_v2)

[[5.07043885e-315 0.00000000e+000]
 [4.94065646e-324 6.59055706e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [3]:
import numpy as np

# build an array with values ranging from 10 to 49.

arr_range_v2 = np.arange(10,50)
print("Matrix from 10-49: ",arr_range_v2)

# build a 3X3 matrix with values ranging from 0 to 8.

arr_3x3_range_v2 = np.arange(0,9).reshape((3,3))
print("3 x 3 matrix from 0-8: ", arr_3x3_range_v2)

# build a 3X3 identity matrix.

arr_3x3_identity_v2 = np.eye(3,3)
print("3 x 3 identity matrix: ",arr_3x3_identity_v2)

# build a random array of size_v2 30 and determine the mean of the array.

arr_random_v2 = np.random.random(30)
print("Random array of size_v2 30: ", arr_random_v2)

# build a 10X10 array with random values and determine the minimum and maximum values.

arr_rand_10x10_v2 = np.random.rand(10, 10)
print("Random 10 x 10 matrix: ", arr_rand_10x10_v2)
max_v2 = arr_rand_10x10_v2.max()
min_v2 = arr_rand_10x10_v2.min()
print("Max is:", max_v2)
print("MIn is:", min_v2)

# build a zero array of size_v2 10 and replace 5th element with 1.

arr_zero_10_v2 = np.zeros(10)
arr_zero_10_v2[4] = 1
print("Zero array of size_v2 10 with 5th element as 1: ", arr_zero_10_v2)

# Reverse an array arr_v2 = [1,2,0,0,4,0].

arr_v2 = [1,2,0,0,4,0]
arr_reversed_v2 = np.array(arr_v2)[::-1]
print("Reversed array: ", arr_reversed_v2)

# build a 2d array with 1 on border and 0 inside.

arr_2d_v2 = np.zeros((2,2))
bordered_arr_v2 = np.pad(arr_2d_v2, pad_width = 1, mode='constant', constant_values=1)
print("Bordered array: \n", bordered_arr_v2)

# build a 8X8 matrix and fill it with a checkerboard pattern.

checkerboard_arr_v2 = np.indices((8, 8)).sum(axis=0) % 2
print("Checkerboard_arr: \n", checkerboard_arr_v2)

Matrix from 10-49:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3 x 3 matrix from 0-8:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
3 x 3 identity matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array of size_v2 30:  [0.8802975  0.87243967 0.21220988 0.59675709 0.23896572 0.63242958
 0.21643969 0.34086821 0.23545499 0.86207712 0.33310596 0.89712123
 0.73281508 0.073318   0.39740343 0.95270699 0.10575215 0.20683591
 0.51702551 0.50122951 0.76642756 0.30300823 0.2378554  0.05634672
 0.83602898 0.7484111  0.18121129 0.13075734 0.84786526 0.26211376]
Random 10 x 10 matrix:  [[0.40916639 0.02510908 0.31068305 0.23799304 0.3151647  0.48881609
  0.55078863 0.08454845 0.14904903 0.11622738]
 [0.65211367 0.83813121 0.23485917 0.67116952 0.0323333  0.18934738
  0.67616457 0.84625757 0.27138224 0.23621884]
 [0.82841149 0.21551451 0.08879097 0.47649335 0.66216713 0.52425185
  0.24614859 0.54378408 0.5275397  0.0567776 ]
 [0.620631

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [4]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# Adding the two arrays

add_2x2_v2 = np.add(x,y)
add_1x2_v2 = np.add(v,w)
print("Addition of x and y: \n", add_2x2_v2)
print("Addition of v and w: ", add_1x2_v2)

# Subtracting the two arrays

sub_2x2_v2 = np.add(x,-y)
sub_1x2_v2 = np.subtract(v,w)
print("Substraction of x and y: \n", sub_2x2_v2)
print("Substraction of v and w: ", sub_1x2_v2)

# Multiplying the array with any integers of my choice

mul_num_v2 = 2
mul_arr_x_v2 = np.multiply(x,mul_num_v2)
print(f"Multiplying x with {mul_num_v2} : \n", mul_arr_x_v2)

# determine the square of each element of the array.

sqr_arr_y_v2 = np.power(y, 2)
print("Square of array y is: \n", sqr_arr_y_v2)

# determine the dot product between: v(and)w ; x(and)v ; x(and)y.

dot_x_y_v2 = np.dot(x,y)
dot_v_w_v2 = np.dot(v,w)
dot_x_v_v2 = np.dot(x,v)
print("Dot product of x and y: \n", dot_x_y_v2)
print("Dot product of v and w: \n", dot_v_w_v2)
print("Dot product of x and v: \n", dot_x_v_v2)

# Concatenate x(and)y along row and Concatenate v(and)w along column.

concat_x_y_v2 = np.concatenate((x,y),axis=0)
stack_x_y_v2 = np.vstack((x,y))
stack_v_w_v2 = np.hstack((v,w))
print("Concatination of x and y along row: \n", concat_x_y_v2)
print("Stacking of x and y along row: \n", stack_x_y_v2)
print("Stacking of v and w along row: \n", stack_v_w_v2)

# Concatenate x(and)v

# concate_x_v = np.concatenate((x,v),axis=0)

Addition of x and y: 
 [[ 6  8]
 [10 13]]
Addition of v and w:  [20 22]
Substraction of x and y: 
 [[-4 -4]
 [-4 -3]]
Substraction of v and w:  [-2 -2]
Multiplying x with 2 : 
 [[ 2  4]
 [ 6 10]]
Square of array y is: 
 [[25 36]
 [49 64]]
Dot product of x and y: 
 [[19 22]
 [50 58]]
Dot product of v and w: 
 219
Dot product of x and v: 
 [29 77]
Concatination of x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Stacking of x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Stacking of v and w along row: 
 [ 9 10 11 12]


The code had a ValueError as the dimensions of both the array is not the same. The array x has the dimensions of 2x2 but array v has the dimensions of 1x2.

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT.

In [5]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Prove A.A−1 = I.

A_inverse_v2 = np.linalg.inv(A)
mul_A_Ainv_v2 = np.dot(A, A_inverse_v2)
print("Multiplication of A and A_inverse_v2: \n", mul_A_Ainv_v2)
idenity_matrix_v2 = np.eye(A.shape[0])
print("Identity matrix: \n", idenity_matrix_v2)
is_identity_v2 = np.allclose(mul_A_Ainv_v2, idenity_matrix_v2)
if(is_identity_v2):
    print("The matrix multiplication of A and its inverse is an Identity matrix or close to it.")
    print("Hence Proved.")
else:
    print("Not Proved.")

# Prove AB ̸= BA.

mul_AB_v2 = np.matmul(A,B)
mul_BA_v2 = np.matmul(B,A)
print("Multiplication of A and B: \n", mul_AB_v2)
print("Multiplication of B and A: \n", mul_BA_v2)
equal_mul_v2 = np.array_equal(mul_AB_v2, mul_BA_v2)
if(not equal_mul_v2):
    print("The matrix multiplication of A and B is not equal to the matrix multiplication of B and A.")
    print("Hence Proved.")
else:
    print("The matrix multiplication of A and B is equal to the matrix multiplication of b and A.")
    print("Not proved.")

# Prove (AB)T = BTAT

A_transpose_v2 = np.transpose(A)
B_transpose_v2 = np.transpose(B)
AB_transpose_v2 = np.transpose(mul_AB_v2)
print("The Transpose of AB ((AB)T) is: \n", AB_transpose_v2)
B_trans_A_trans_v2 = np.matmul(B_transpose_v2, A_transpose_v2)
print("The Transpose of B multiplied with Transpose of A (BTAT) is: \n", B_trans_A_trans_v2)
equal_trans_v2 = np.array_equal(AB_transpose_v2, B_trans_A_trans_v2)
if(equal_trans_v2):
    print("The transpose of AB and transpose of B multiplied with transpose of A is equal.")
    print("Hence Proved.")
else:
    print("Not Proved.")

Multiplication of A and A_inverse_v2: 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix: 
 [[1. 0.]
 [0. 1.]]
The matrix multiplication of A and its inverse is an Identity matrix or close to it.
Hence Proved.
Multiplication of A and B: 
 [[23 13]
 [51 29]]
Multiplication of B and A: 
 [[36 44]
 [13 16]]
The matrix multiplication of A and B is not equal to the matrix multiplication of B and A.
Hence Proved.
The Transpose of AB ((AB)T) is: 
 [[23 51]
 [13 29]]
The Transpose of B multiplied with Transpose of A (BTAT) is: 
 [[23 51]
 [13 29]]
The transpose of AB and transpose of B multiplied with transpose of A is equal.
Hence Proved.


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [6]:
import numpy as np

# representing in augmented matrix form

# Matrix of coefficients

a = [
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
    ]
A = np.array(a)

# Matrix of constants

b = [-1,-3,9]
B = np.array(b)

# with inverse method

A_inverse_v2 = np.linalg.inv(A)
X = np.matmul(A_inverse_v2, B)
print("The value of x, y, z is: \n", X)

The value of x, y, z is: 
 [ 2.  1. -2.]


Experiment: How Fast is Numpy?

1. Element-wise Addition
2. Element-wise Multiplication
3. Dot Product
4. Matrix Multiplication

In [12]:
import numpy as np
import random
from timeit import timeit

# Creating two different lists of size_v2 1000000

size_v2 = 1000000
A_list_v2 = random.sample(range(size_v2 + 1), size_v2)
B_list_v2 = random.sample(range(size_v2 + 1), size_v2)
A_array_v2 = np.array(A_list_v2)
B_array_v2 = np.array(B_list_v2)

# Python addition

def python_add(A, B):
    result_v2 = []
    for i in range(len(A)):
        result_v2.append(A[i] + B[i])
    return result_v2
python_time_add_v2 = timeit("python_add(A_list_v2, B_list_v2)", globals=globals(), number=100)
print("Python time for add:", python_time_add_v2)

# Numpy addition

def numpy_add(A, B):
    return A + B
numpy_time_add_v2 = timeit("numpy_add(A_array_v2, B_array_v2)", globals=globals(), number=100)
print("Numpy time for add:", numpy_time_add_v2)

# Python multiplication

def python_mul(A, B):
    result_v2 = []
    for i in range(len(A)):
        result_v2.append(A[i] * B[i])
    return result_v2
python_time_mul_v2 = timeit("python_mul(A_list_v2, B_list_v2)", globals=globals(), number=100)
print("Python time for multiplication:", python_time_mul_v2)

# Numpy multiplication

def numpy_mul(A, B):
    return np.multiply(A, B)
numpy_time_mul_v2 = timeit("numpy_mul(A_array_v2, B_array_v2)",globals=globals(), number=100)
print("Numpy time for multiplication:", numpy_time_mul_v2)

# Python dot product

def python_dot(A, B):
    return sum(a * b for a, b in zip(A, B))
python_time_dot_v2 = timeit("python_dot(A_list_v2, B_list_v2)", globals=globals(), number=100)
print("Python time for dot product:", python_time_dot_v2)

# Numpy dot

def numpy_dot(A, B):
    return np.dot(A, B)
numpy_time_dot_v2 = timeit("numpy_dot(A_array_v2, B_array_v2)", globals=globals(), number=100)
print("Numpy time for dot product:", numpy_time_dot_v2)

# Matrix creation

matrix_size_v2 = 300
Z1_matrix_list_v2 = [A_list_v2[i:i + matrix_size_v2] for i in range(0, matrix_size_v2**2, matrix_size_v2)]
Z2_matrix_list_v2 = [B_list_v2[i:i + matrix_size_v2] for i in range(0, matrix_size_v2**2, matrix_size_v2)]
Z1_matrix_arr_v2 = np.array(Z1_matrix_list_v2)
Z2_matrix_arr_v2 = np.array(Z2_matrix_list_v2)

# Python matrix multiplication

def python_matmul(A, B):
    return [
        [sum(a * b for a, b in zip(row_A, col_B)) for col_B in zip(*B)]
        for row_A in A
    ]
python_time_matmul_v2 = timeit(
    "python_matmul(Z1_matrix_list_v2, Z2_matrix_list_v2)",
    globals=globals(),
    number=10
)
print("Python time for matrix multiplication:", python_time_matmul_v2)

# Numpy matrix multiplication

def numpy_matmul(A, B):
    return np.matmul(A, B)
numpy_time_matmul_v2 = timeit(
    "numpy_matmul(Z1_matrix_arr_v2, Z2_matrix_arr_v2)",
    globals=globals(),
    number=10
)
print("Numpy time for matrix multiplication:", numpy_time_matmul_v2)

Python time for add: 36.183017534000044
Numpy time for add: 0.17565670499999442
Python time for multiplication: 36.21087646800004
Numpy time for multiplication: 0.3658581210000307
Python time for dot product: 34.04429000499999
Numpy time for dot product: 0.18071074700003464
Python time for matrix multiplication: 65.24796672500003
Numpy time for matrix multiplication: 0.3575306960000262
